{% set version = "0.3.1" %}

package:
  name: wrenfold
  version: {{ version }}

source:
  url: https://github.com/wrenfold/wrenfold/releases/download/v{{ version }}/wrenfold-source-v{{ version }}.tar.gz
  sha256: ec0515044d1070a0494e31fc946752a3986cd7a05f394b8c4a0d8cd44ba6f456

build:
  number: 0

requirements:
  build:
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - cmake >=3.20,<3.28  # [build_platform != target_platform]
    - ninja  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - python
    - scikit-build-core ==0.10.7
    # Use cmake<3.28 to avoid clang-scan-deps dependency on OSX (introduced with CMake 3.28).
    - cmake >=3.20,<3.28
    - ninja
    - pip
  run:
    - python

test:
  imports:
    - wrenfold
    - wrenfold.sym
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/wrenfold/wrenfold
  summary: Toolkit for generating code from symbolic math expressions.
  license: MIT
  license_file:
    - LICENSE
    - dependencies/abseil-cpp/LICENSE
    - dependencies/fmt/LICENSE
    - dependencies/pybind11/LICENSE
  doc_url: https://wrenfold.org

extra:
  recipe-maintainers:
    - gareth-cross
