{% set version = "0.1.0" %}

package:
  name: wrenfold
  version: {{ version }}

source:
  url: https://github.com/wrenfold/wrenfold/releases/download/v{{ version }}/wrenfold-source-v{{ version }}.tar.gz
  sha256: c621dff6173822e165c112ea9ff491ecb3a5f16b01aedd890614fb1811e05a5a

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - scikit-build-core ==0.9.8
    - cmake >=3.20
    - ninja >=1.5
    - mypy ==1.9.0
    - pip
  run:
    - python

test:
  imports:
    - wrenfold
    - wrenfold.sym
  requires:
    - pip
    - numpy
    - sympy
  source_files:
    - components/wrapper/tests/*.py
    - examples/**/*.py
    - support/test_wheel.py
  commands:
    - pip check
    - python support/test_wheel.py

about:
  home: https://github.com/wrenfold/wrenfold
  summary: Toolkit for generating code from symbolic math expressions.
  license: MIT
  license_file:
    - LICENSE
    - dependencies/abseil-cpp/LICENSE
    - dependencies/fmt/LICENSE
    - dependencies/pybind11/LICENSE
  doc_url: https://wrenfold.org

extra:
  recipe-maintainers:
    - gareth-cross
